### ISSUE TITLE
Delayed jobs are not being promoted correctly (stuck in a delayed state)

### ISSUE THREAD

**Issue by hathvi** [LearnBoost/kue#312]
https://github.com/LearnBoost/kue/blob/master/lib/kue.js#L151

Since it only fetches the promoters limit of jobs sorted by their delay time with no reference to the time the job was actually created, there's no way to accurately say there's no other jobs with a delay time that has been exceeded if your delay list is larger then the promoters limit. With the default settings I could create 200 jobs delayed across a 1 week period, then delay the 201st job for 1 week 1 day. As long as I keep 200 jobs with a delay time < 1 week in a delayed state, that 201st job will never get promoted even though the delay time has been exceeded. If a couple of months have passed, and all of a sudden I didn't have at least 200 jobs in a delayed state, that 201st job would finally get queued months after I would have expected it to.

I would have assumed this would work more along the lines of a promote_at timestamp. When delay is called on a job, it would calculate this timestamp based on the created_at + the milliseconds passed to the delay function. The promoter could then sort by the promote_at timestamp and check each job to get the time in milliseconds that have exceeded and promote as needed.

# Example #
```javascript
var kue = require('kue'),
    jobs = kue.createQueue();

kue.app.listen(3000);

var jobType = 'test',
    promotionTime = 1000,
    promotionLimit = 1;

// simply creates a delayed job
var createDelayedJob = function(ms, title) {
  jobs.create(jobType, { title: title }).delay(ms).save();
};

// a working job is a job that has a delay time less then
// that of our failing job
var createWorkingJob = function() {
  createDelayedJob(promotionTime, 'I should get queued');
};

// a failing job is a job that has a delay time greater then
// the delay of the promotionLimit of jobs in a delayed state
var createFailingJob = function() {
  createDelayedJob(promotionTime * 10, 'I never get queued');
};

for (var i = 0; i < promotionLimit; i++) {
  createWorkingJob();
}

createFailingJob();

jobs.process(jobType, promotionLimit, function(job, done) {
  createWorkingJob();

  setTimeout(function() { 
    done();
  }, promotionTime);
});

jobs.promote(promotionTime, promotionLimit);

```

**Comment by Incognito** [comment]
+1 for some attention on this bug. I was really hopeful I could use this feature as the core of what I'm making but it just simply will not change to the inactive state after the time delay. It may be worth mention that a delay value of '0' has no problem running.

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/352
