### ISSUE TITLE
[UI] Delayed task stuck on "less than one second"

### ISSUE THREAD

**Issue by grabbou** [LearnBoost/kue#352]
I have a job with 5 attempts and backoff timeout - 1 minute. For the first error, the task is moved to delayed with counter which is correct. Then, the counter stops on less than one second and task is being moved to 'active' tab. 

When there is an error again (2 from 5 attempts allowed), the task appears in delayed tab again but the counter does not fire again and I am stuck with 'less than one second' even if there is still almost one minute left. 

After one minute, the task is correctly moved to active tab so I believe this problem is only UX related.

Any other counters and stats (attempts, created, updated etc. are being calculated correctly).

**Comment by bradvogel** [comment]
Seeing this also. Code?

**Comment by grabbou** [comment]
I do not have an access to that code anymore :( I will try to find old Github commits from the past and recover that build somehow. Give me ~3 days.
