### ISSUE TITLE
Is there an advised way to handle jobs that get stuck in an active state?

### ISSUE THREAD

**Issue by dbousamra** [LearnBoost/kue#391]
I have a situation where a worker picks a job up, starts processing it, and then in the middle of processing, I get a fatal process error (due to bad OpenCV errors I can't seem to catch). PM2 restarts the app, and continues processing.

However, that job has been marked as active, and is now stuck.

Is there a way to clear out active jobs, pushing them back to failed if they are in an active state too long?

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/544

**Comment by behrad** [comment]
Document on using domains #403 and why Kue has not used them builtin !?
