### ISSUE TITLE
Document performance tip: redis memory consumption optimization

### ISSUE THREAD

**Issue by 256dpi** [LearnBoost/kue#402]
I started using kue in a production system that generates ~100'000 jobs a day. After processing 70'000 jobs the redis memory usage has increased by 250MB which is huge compared to another app using sidekiq (~2MB).

Is there an option to limit the memory usage, remove completed jobs or maybe store the data differently?

**Comment by crashbell** [comment]
Can you tell me the difference between `job.removeOnComplete(true)` and @256dpi suggestion? So far I'm using `job.removeOnComplete(true)` and you can see  `q:job:*` keys are not removed. 

![screen shot 2015-01-14 at 7 21 08 pm](https://cloud.githubusercontent.com/assets/810139/5738821/7beb71ae-9c23-11e4-9179-0106955954bf.png)

**Comment by behrad** [comment]
`removeOnComplete` is a shorthand internal implementation which doesn't have the `Job.get` roundtrip. 
If you are sure those 2347 keys under q:job are all `completed` jobs which should have been deleted, please try to report a BUG + test case producing it @crashbell

**Comment by behrad** [comment]
Since search indexes are planned to be disabled by default... this is not necessary to add this

**Comment by crashbell** [comment]
so I will wait for new version of Kue to get rid of this issue. Is it correct?

**Comment by behrad** [comment]
you can simulate the upcoming 0.9.0 release by adding `disableSearch: true` option @crashbell  but your issue seems something different that this topic :) huh!?

**Comment by crashbell** [comment]
yes @behrad, sorry about that. My issue is definitely different. I will log a new issue if I find it necessary. Thank you!
