### ISSUE TITLE
Disable search indexes by default

### ISSUE THREAD

**Issue by behrad** [LearnBoost/kue#412]
1) They are leaky on job removal
2) They waste memory when not needed
3) They create their own (reds module) redis connections, which is not controlled by kue. That currently causes node.js process not to exit after shutdown

**Comment by bradvogel** [comment]
The readme doesn't really explain what the search indexes are for. What's the tradeoff of disabling them? Will the UI still work?

**Comment by behrad** [comment]
search indexes mainly was built for UI,
tradeoff of enabling them is higher memory consumption and sometimes leaking indexes, and more (unmanaged by Kue) connections to redis.


> Will the UI still work?

unfortunately NO! :(

**Comment by bradvogel** [comment]
OK thanks. But I'm noticing the UI still updates with search indexes turned off. Can you describe what parts of the UI won't work with this turned off?

**Comment by behrad** [comment]
which version are you on? how are you bootstrapping your ui ?

**Comment by behrad** [comment]
> Can you describe what parts of the UI won't work with this turned off?

the search text field

**Comment by bradvogel** [comment]
0.8.12. But that makes sense that just the search text field doesn't work. The rest of the UI seems to function fine.

**Comment by behrad** [comment]
this is merged with latest (0.9.0) not the 0.8.12 so in your Kue also the search text field should work as before :)


> The rest of the UI seems to function fine.

sure, it sould
