### ISSUE TITLE
document job.removeOnComplete( true )

### ISSUE THREAD

**Issue by behrad** [LearnBoost/kue#439]

**Comment by bradisbell** [comment]
@wachunga `removeOnComplete` only removes completed successful jobs for me.  Failed jobs remain in the queue to be investigated later.  Perhaps you have something else removing your failed jobs, your jobs are not failing, or they are being re-tried and then completed?

**Comment by wachunga** [comment]
@bradisbell You're right: it only removes successful jobs. Apologies for the mistake. So the method name is perfect :)

I suppose removeOnFailed could still be useful for some use cases, but it's not something I currently care about.

**Comment by bradvogel** [comment]
Is there a way to use 'removeOnComplete' when POSTing a new job via HTTP?

**Comment by bradisbell** [comment]
@bradvogel Simply specify `removeOnComplete` in the options:

```json
{
  "type": "someJobType",
  "data": {
    "somethig": "something"
  },
  "options": {
    "attempts": 4,
    "removeOnComplete": true
  }
}
```

**Comment by bradvogel** [comment]
Oh, thanks!
