### ISSUE TITLE
enqueue event never fires

### ISSUE THREAD

**Issue by metalaureate** [LearnBoost/kue#498]
I can't get `enqueue` to fire when a job is added to the queue. E.g.,

```
      job.on('enqueue', function () {
            conn.query("UPDATE users SET last_montage_processed_date=NOW() WHERE user_uuid=$1",[user_uuid], function (error, result) {
                if (error) throw error;
            });
        });
```

`progress` and 'complete` work fine.

**Comment by behrad** [comment]
there's no `job.on( 'enqueue',...) ` 
enqueue event is emitted globally on queue object. You should use `jobs.on( 'enqueue' )` @metalaureate

**Comment by metalaureate** [comment]
Sorry for misunderstanding - thanks for clarification. Out of interest, is there a good architectural reason not to have a `job.on('start',...) event?

**Comment by behrad** [comment]
We could have `job.on('start')` however as mentioned in documentation, job level events are not survived from a restart and are local to the process having job instance :)
