### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by tianp** [LearnBoost/kue#499]
On my production server, I got error message as follow:

```
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

Any idea why and how to fix this?

Thank you.

**Comment by behrad** [comment]
it shows a connection timeout, Kue only needs to connect to redis, and it seems your redis server is not accessible from kue :)
