### ISSUE TITLE
Precisely half of the jobs get processed.

### ISSUE THREAD

**Issue by bwang29** [LearnBoost/kue#503]
I'm using the latest kue in node.js. Right now precisely half of the jobs are picked up by polarr_jobs.process() although all request can be seen as active/completed in the Kue UI.

For example, the first time a job is submitted to kue, it shows up and stuck in Active
the second job is submitted to kue, it shows up in Active, then completed
the third job is submitted to kue, it shows up and stuck in Active
the forth job is submitted to kue, it shows up in Active, then completed
so on and so forth..

What might be the issue?

**Comment by behrad** [comment]
There should be some error in your process callback which occasionally prevents `done` to be called, so job get's stuck in active. those stuck active jobs keep your concurrency bandwidth and process will not accept new jobs a bit later...

**Comment by micahlmartin** [comment]
IS there a solution to this? This is constantly happening to me where something is going wrong in the jobs and then they just sit their in an active state and no new jobs can be picked up. This seems like a massive issue.

**Comment by behrad** [comment]
this will seem a massive issue unless you are properly handling errors in your code @micahlmartin 
You can use 
 - domains
 - promises error handling
 - process uncaught error handlers

please read https://github.com/LearnBoost/kue/issues/391 and https://github.com/LearnBoost/kue/pull/403 or even https://github.com/LearnBoost/kue/issues/130#issuecomment-42478711

**Comment by bwang29** [comment]
This issue can be closed now. It happened that we had another "left-over" server listening to the Kue and that server is running old, bad code.  The kue accepts the jobs correctly. Apologize for not figuring out by ourselves.
