### ISSUE TITLE
[Documentation] When are job events unreliable?

### ISSUE THREAD

**Issue by wearhere** [LearnBoost/kue#506]
Hi, I'm wondering if there's a typo in this line from the ["Job Events"](https://github.com/LearnBoost/kue#job-events) section of the documentation:

> Note that Job level events are not guaranteed to be received upon worker process restarts, since the process will lose the reference to the specific Job object.

Should that read _master_ process restarts? (The process that schedules the jobs?) I'm not sure why the worker processes going down would lead to the master's reference to the job becoming invalid.

**Comment by behrad** [comment]
You are completely right @wearhere Thank you for finding this out :+1:

**Comment by wearhere** [comment]
Cool, thanks for the quick response!
