### ISSUE TITLE
Document 'error' event?

### ISSUE THREAD

**Issue by bradvogel** [LearnBoost/kue#508]
I noticed that the queue emits an 'error' event here https://github.com/LearnBoost/kue/blob/master/lib/queue/worker.js#L91. Should this be documented?

**Comment by behrad** [comment]
actually currently all worker errors are re-emitted into `kue` object itself (see https://github.com/LearnBoost/kue/blob/master/lib/kue.js#L239) this is not to face uncaught exceptions when consumers forget to listen for `error` in each workers they create.

I considered this not a stabled decision at that time and so not added this into documentation.

**Comment by behrad** [comment]
closed by https://github.com/LearnBoost/kue/issues/409
