### ISSUE TITLE
"Redis connection gone from end event" error

### ISSUE THREAD

**Issue by bradvogel** [LearnBoost/kue#511]
I'm occasionally getting the error `Redis connection gone from end event` when calling `job.remove()`. This appears to be fixed in redis v0.11 (https://github.com/mranney/node_redis/issues/247). Kue appears to still be using v0.10.

I upgraded locally and the tests passed fine. Let me know and I can file a quick PR.

**Comment by behrad** [comment]
that would look good @bradvogel , BTW the issue you mentioned is still open, looks unresolved huh ?

**Comment by bradvogel** [comment]
I was hoping either "Set socket_keepalive to prevent long-lived client timeouts." in release v0.11 or "Fix unix socket support" in v0.12 would fix this. Filed https://github.com/LearnBoost/kue/pull/512/files

**Comment by behrad** [comment]
anyway I think keeping `node_redis` to the most recent stable version is a very good idea, thanks @bradvogel
