### ISSUE TITLE
Question on watchStuckJobs + promote

### ISSUE THREAD

**Issue by davisford** [LearnBoost/kue#513]
I have multiple processes, something like this:

* master-web-server (receives jobs from workers2+3, produces jobs for worker4)
* worker1 (receives jobs from master, produces jobs for master)
* worker2 (receives jobs from master, produces jobs for master)
* worker3 (receives jobs from master)

I have been experiencing stuck jobs, and I am combing through the comments/issues to try to figure out how to make this more robust.  I have added graceful shutdown to all of these processes, so that should help.

Other suggestions indicate that you should call `jobs.watchStuckJobs()`, but should I call that in each process or just the master?

Same question for `jobs.promote()` -- call in each process or just the master?  

I should clarify, it is my understanding that you only need to call `promote` if you are using delayed jobs, **OR** if you are using retries (i.e. `.attempts(x)`) since that uses delays under the covers.

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/510#issuecomment-74639328
+ 
both those methods do a global server side change on redis, so both need to be called in only ONE (i.e. your master) process.

whenever you need a delay (be in delayed or delayed retries) you need promote to be called :)

**Comment by davisford** [comment]
thanks
