### ISSUE TITLE
Delayed jobs never start

### ISSUE THREAD

**Issue by webchaz** [LearnBoost/kue#515]
I'm having a problem when declaring a delayed job, they never actually start.  This is my code for defining a delayed job, this should start after 5 seconds, but instead it just stays in delayed forever (at least 20min).  If I remove the `.delay(5000)` then it runs right away as expected. 

```
 var job = kue.jobs.create('email', options).save(function(err){
     if(!err) console.log(job.id);
  }).delay(5000).priority('high').save();
```

```
kue.jobs.process('email', function(job, done){
  console.log(job);
  done();
});
```

The only thing different I have is the `prefix` option, if it makes a difference.

```
kue.jobs = kue.createQueue({
  prefix: 'qs'
});
```

**Comment by behrad** [comment]
I wonder if you have read the documentation carefully and called `promote()`
