### ISSUE TITLE
Support for multiple servers?

### ISSUE THREAD

**Issue by chainlink** [LearnBoost/kue#516]
We have Kue running on one server and it's great, but is there a way to scale it to more servers? Would I just run the jobs.process code on more than one box?

**Comment by behrad** [comment]
> Would I just run the jobs.process code on more than one box?

why not :)

**Comment by chainlink** [comment]
There should be any issues with job contention if they're all connecting to the same Redis server right?

**Comment by behrad** [comment]
thanks redis atomic BLPOP, there would be no problem about many consumers listening for poping jobs

**Comment by luislobo** [comment]
For some reason, I have had trouble doing that. I'll try to create a sample project and post it. I mentioned this on my #504 issue

**Comment by behrad** [comment]
then I close this as a duplicate issue, please post details on the other issue :)
