### ISSUE TITLE
Is kue using redis recommended client?

### ISSUE THREAD

**Issue by rahpuser** [LearnBoost/kue#517]
I'm wondering if kue is using as default redisClient the node_redis library that is the recommended library by redis.io ? ( https://github.com/mranney/node_redis )

**Comment by behrad** [comment]
you could check package.json (https://github.com/LearnBoost/kue/blob/master/package.json#L19) and find that we are using the famous node_redis

**Comment by rahpuser** [comment]
ok, I will. Thank you
