### ISSUE TITLE
clear queue

### ISSUE THREAD

**Issue by pradeep-mishra** [LearnBoost/kue#520]
is there any way to clear all pending tasks from queue ?

**Comment by behrad** [comment]
I searched them for you, please read https://github.com/LearnBoost/kue/issues/58#issuecomment-54267574 and https://github.com/LearnBoost/kue/issues/335#issuecomment-43629107

**Comment by pradeep-mishra** [comment]
thanks maybe rangeByType can help
isnt there any inbuilt function like kue.clear('queue name') or kue.purge('queue name')  ?

**Comment by behrad** [comment]
no not yet unfortunately, you can request one in the related job maintenance API issue
