### ISSUE TITLE
"started" event when a job begins processing

### ISSUE THREAD

**Issue by johnaschroeder** [LearnBoost/kue#523]
I'm looking for a simple way to create a TTL for each job to protect against a long-running process dying and swallowing done() so it's never called.  I currently have one Kue server that handles job creation POSTs from several different servers/languages and serves the kue UI.  Jobs are then processed by a bunch of node servers.  

I have TTL working, but had to insert:    ``` self.emitJobEvent('started', job); ``` in Worker.prototype.start after the call to Worker.process when one of the node servers has found a new job.  

I then listen for that event and set a TTL on the job in the main Kue server app.js like so: 
```
var maxProcessingTime = 10* 60 * 1000;
var jobTimeouts = {};
zimQueue.on('job started', function(id, type){
    console.log("job started: ", id);
    kue.Job.get(id, function(err, job){
        if (err) { return; }
        jobTimeouts[id] = setTimeout(function(){
            job.inactive(function(err){
                if (err) { throw err; }
                console.log(type, ' job timed out, restarting id: #%d', job.id);
            });
        }, maxProcessingTime);
    });
});
```
It seems to work fine, but I'd prefer not to mess with the source.  A few questions: is there a simpler/more reliable way to do this?  Does it make sense to have a "started" event? Happy to pull if so... 

I noticed TTL is on the roadmap, any thoughts on how/when that might be implemented?  This might work okay for now, but could get hairy as the volume grows.

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/391
https://github.com/LearnBoost/kue/issues/529
