### ISSUE TITLE
Filling Up Redis

### ISSUE THREAD

**Issue by chainlink** [LearnBoost/kue#528]
Does Kue manage the memory it's using in Redis at all? (Ie. Will it just keep filling Redis until Redis is out of memory?)

I've set maxmemory and allkeys-lru to offset this, but is there a better strategy?

**Comment by behrad** [comment]
Kue is doing nothing for you :) you create jobs, you are to clean them up when you want to
However, if you don't need complete job data/history, you can set `removeOnComplete(true)` on jobs so that kue deletes them on completion and your memory won't shirink

**Comment by chainlink** [comment]
ok thanks!
