### ISSUE TITLE
Feature request: producer side API: job.timeout(millis)

### ISSUE THREAD

**Issue by osher** [LearnBoost/kue#529]
I'll elaborate using a snippet

```
var data = 
    { from    : "me@gmail.com"
    , to      : "you@gmail.com"
    , subject : "hello!!"
    , body    : "wassuuuuup"
    , title   : "mail from me to you"
    }
  , job1 = 
    kue.create('email', data)
       .timeout(15000) //means - if the job is not done in 15 sec - let it fail with reason "timeout"
       .save()
  , job2 = 
    kue.create('email', data)
       .attempts(5)
       .timeout(5000, 7500, 15000) //means - if 1st attempt is not done in 5 sec - let it fail with reason "timeout"
                                   //if 2nd attempt is not done in 7.5 sec - let it fail with reason "timeout" 
                                   //if 3nd attempt is not done in 15 sec - let it fail with reason "timeout" 
                                   //any attempt after - takes the last timeout, in this case 15 sec
       .save()
  ;
````

nice-to-have - 
   when value is a number - it's millis
   string - will be interperted "5s" -> 5000, "2m" --> 120000,  "0.5h" -> 3600000, etc.

even nicer to have - 
    consumer should be able to reschedule timeouts using the same API (api complies to the job's own statemachine).

Why? because if a job errors without calling next() - it gets hung.
Seems to me legible for an infrastructure to offer such a solution ;)

**Comment by behrad** [comment]
thank you @osher this smells exactly the TTL feature which Kue is about to have on next minor releases and is missing now REALLY!
Any PR's can make it happen sooner and will be discussed upon :)

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/544
