### ISSUE TITLE
clarification: shutting down without stopping workers

### ISSUE THREAD

**Issue by lepinsk** [LearnBoost/kue#530]
I'm trying to figure out how to gracefully shutdown a Kue instance *without* instructing worker processes to shut down. From [the documentation](https://github.com/learnboost/kue#graceful-shutdown), it seems that ```Queue#shutdown(fn, timeout)``` sends a signal to all workers to shutdown.

Our architecture is such that workers are running on separate, isolated machines. From time to time, the server process controlling these workers will be restarted, but we don't want that to have any effect on the workers or any active jobs they're processing. Really, we just want to get Kue to disconnect cleanly from our Redis host before the server restarts.

Am I right in understanding that ```Queue#shutdown``` doesn't function like this? How would you suggest accomplishing what we're trying to do?

**Comment by behrad** [comment]
> Am I right in understanding that Queue#shutdown doesn't function like this?

Yup you're right
And this is not safe to consider workers keeping on while redis and the master process restarting... since workers can change jobs anytime in the middle of the process, or even kue can update jobs while they are being processed....

> How would you suggest accomplishing what we're trying to do?

I think you should fundamentally rethink or change your design on this specific problem. whats your limits? 
why you don't want kue to shutdown (= stop workers) on redis restarts?
who can you escape/rearrange redis restarts?

**Comment by lepinsk** [comment]
Thanks for the reply. Our architecture is such that jobs are created on one server (master), which spins up transient additional servers (processors) to consume and process these jobs. Each server runs a copy of Kue and connects to the same Redis database, obviously. 

The processor servers take anywhere between 1-5 minutes to run jobs, at which point they mark jobs as complete, shut down, and are destroyed. (We're paying by the second for these servers, and they cost a lot, which is why they only exist to run a job, before they're terminated.)

Jobs don't get updated by the master server once they've been enqueued.

The problem we have is that our PaaS provider (Heroku) randomly cycles each running server approximately once every 24 hours. Heroku sends a ```SIGTERM``` to our master process, which gives it 10 seconds to gracefully shut down itself – otherwise Heroku will forcefully stop the process with a ```SIGINT```. The server is immediately restarted. It is entirely possible that Heroku may send this ```SIGTERM``` to the master server while a processor server is working on a job. *Currently* we shut down less-than-gracefully, allowing the server process to be ```SIGINT```ed, before restarting. This doesn't seem to have any ill effects on Kue, but we thought it might be possible to more gracefully disconnect from Redis before going down for a restart.

**Comment by behrad** [comment]
I don't see whats behind your issue, but you can simply gracefully shutdown kue node on receiving SIGTERM, after restarts you can lookup for failed jobs tagged `shutdown` and re-activate them making sure you are preventing racing of restarting nodes on this :)

**Comment by lepinsk** [comment]
Hey @behrad,

Thanks for the info – I appreciate it. We've got some things to think about. I'll mark this as closed.

Thanks again.

**Comment by daniellevinson** [comment]
@lepinsk a little trip down memory lane: 
I feel like you've not been fully understood on this issue and I'm having the same question - how do I gracefully shut down one worker when, for example, scaling in? (I want to use autoscaling on AWS)
I haven't done any experimenting yet, but like you said, looks like `Queue#shutdown` would unnecessarily shut down all other healthy workers as well.
A satisfactory outcome for me would be to just marks the current active job as failed, after which it would be picked up by the next healthy worker.
May I ask what solution you've found, if any?

**Comment by behrad** [comment]
@daniellevinson Check out the code inside `Queue#shutdown` which is using `worker#shutdown`.
I think you need that, which is not currently documented or exposed outside

**Comment by daniellevinson** [comment]
@behrad sounds good, I'll take a look, thank you!
