### ISSUE TITLE
Running workers on different server/domains from the main app

### ISSUE THREAD

**Issue by MrDHat** [LearnBoost/kue#531]
Let's say that the main app is running at `a.domain.com` and I want to host workers on a different server say `workers.domain.com`. Is it possible to do this currently?

**Comment by behrad** [comment]
everything is possible @MrDHat until your kue node.s can see and communicate with a Redis instance/cluster

**Comment by MrDHat** [comment]
Oh, so I just need to put up a shared redis instance between the app & the workers, right?

**Comment by behrad** [comment]
yup :)

**Comment by MrDHat** [comment]
Awesome, thanks :)
