### ISSUE TITLE
express dependency 3.1.1/3.1.2 - vulnerable dependencies

### ISSUE THREAD

**Issue by kirrg001** [LearnBoost/kue#534]
hey,

qs 0.5.6 is on the list for vulnerable dependencies.
send@0.1.0 is on the list for vulnerable dependencies.
connect@2.7.5  is on the list for vulnerable dependencies.

all these dependencies are used in 3.1.2 express.
https://nodesecurity.io/advisories
https://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking

correct me when i'm wrong.

thanks for you work!
kirrg

**Comment by behrad** [comment]
wasn't aware of that :) Which version can we silently upgrade to @kirrg001 ?

**Comment by kirrg001** [comment]
if you install nsp, you can check all your deps ````nsp audit-package``` from the shell.
you need to upgrade to:

express (>= 3.11 <  4) || (>= 4.5)

**Comment by behrad** [comment]
thank you @kirrg001 Can you also provide a tested PR with recommended express version?

**Comment by kirrg001** [comment]
yes will do after work ;-)

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/pull/537
