### ISSUE TITLE
kue.createQueue taking 4 redis connections?

### ISSUE THREAD

**Issue by hems** [LearnBoost/kue#535]
With only one instance of kue running i'm seeing 4 connections on redis and i'm wondering if there is an option to reduce the amount of connections?

In development environment i have limited amount of connections which is yielding connection problems when more than a few people are working at the same time, any suggestions on a workaround for this situation?

**Comment by behrad** [comment]
would you please read these first and then ask me further questions you may have?
https://github.com/LearnBoost/kue/issues/366
https://github.com/LearnBoost/kue/issues/143
https://github.com/LearnBoost/kue/issues/127

**Comment by hems** [comment]
@behrad thank you very much for pointing me those out.

It's all clear now, the only thing i did not find is how to turn search indexing is off, if you could point me to that information i would be very thankful.

**Comment by behrad** [comment]
your welcome :)

here it is: https://github.com/LearnBoost/kue#get-jobsearchq

**Comment by hems** [comment]
@behrad thanks!

i'm using the latest version so i believe i don't actually need to turn it off ( :

:8ball:
