### ISSUE TITLE
Version 8.11 does not seem to be published on NPM

### ISSUE THREAD

**Issue by mk-anselme** [LearnBoost/kue#536]
Hi there!

I was getting a occasional "Redis connection gone from end event" and realized kue was using the redis dependency 0.10.0 (similar issues as #511). 

GitHub is now using `redis 0.12.0` in `kue 8.11`. But NPM gives you the old redis 0.10.0 even when you do an `npm install kue@^0.8.11`. 

I can pull directly from the github version but it would be great to have the latest version on npm.

Thanks,

Sam

**Comment by bradvogel** [comment]
+1 please bump

**Comment by behrad** [comment]
there are existing open issues yet that I would liked to add to `0.8.11` before I npm publish it. Kue is late I know ,but i will do some cleanup and close some issues soon and publish it :)

**Comment by behrad** [comment]
0.8.12 published

**Comment by EgoAleSum** [comment]
Please publish 0.9 too :)

**Comment by behrad** [comment]
usally npm publish will be done when issues are closed and backlog gets empty. Currently I'm in the middle of 0.9

**Comment by mk-anselme** [comment]
@behrad @bradvogel : thanks guys!

**Comment by EgoAleSum** [comment]
@behrad oh ok! I thought you updated the package.json after all changes are made. sorry!
