### ISSUE TITLE
allow for `createQueue` to accept redis connection strings

### ISSUE THREAD

**Issue by defunctzombie** [LearnBoost/kue#539]
I find connection strings much easier to work with and pass via ENV config vars.

Something like the following would be nice for devs

```js
var jobs = kue.createQueue({
    redis: 'redis://localhost:6379/db?option1=foo&option2=bar'
});
```

Or even simpler maybe

```js
var jobs = kue.createQueue('redis://localhost:6379/db?option1=foo&option2=bar');
```

Thoughts? Happy to give it a go for PR.

**Comment by behrad** [comment]
It can be added through a backward compatible PR, the first one is more generic and let user mix Kue options with connection string, and the second one can be also supported as a shorthand for the first when no other options are passed

**Comment by defunctzombie** [comment]
Want me to make a PR?

**Comment by behrad** [comment]
why not :)

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/pull/540
