### ISSUE TITLE
Document the arguments to `job failed`

### ISSUE THREAD

**Issue by kevinburkeshyp** [LearnBoost/kue#542]
Does it get an error? Does it get a result?

**Comment by kevinburkeshyp** [comment]
If there is an error, should probably document the README - saying "Job failed" on a failure is sort of useful, but normally you'd want to include some kind of identifying information along with it.

**Comment by kevinburkeshyp** [comment]
Here is my example code:

```coffee
kue   = require 'kue'
queue = kue.createQueue(redis: {host: '127.0.0.1', port: 6379, pass: null})

queue.process 'echo', 30, (job, done) ->
  console.log job
  console.log done
  done new Error "echo error"

queue.on 'job failed', (args...) ->
  console.log args

console.log "creating echo"
queue.create 'echo', {foo: 'bar'}, (args...) ->
  console.log args
```

The only thing that prints is "creating echo". Redis is listening on 127.0.0.1 port 6379, I've double checked twice. No keys are written to Redis.

**Comment by kevinburkeshyp** [comment]
Alright, I got it working by calling `save()` after creating the kue, however, despite calling `done new Error "error"` the `job failed` callback gets hit with the job ID and `null`, so there's that.

**Comment by behrad** [comment]
https://github.com/LearnBoost/kue/issues/461
